version: '3'


services:
  nginx:
    container_name: nginx
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - web

  web:
    container_name: web
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
  
  db:
    container_name: postgres
    image: postgres:13.1-alpine
    environment:
        POSTGRES_DB: new_db
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  redis:
    container_name: redis
    restart: always
    image: redis/redis-stack
    volumes:
      - redis-data:/data
    ports:
      - "6379:6379"
      - "8001:8001"

volumes:
  postgres-data: {}
  redis-data: {}
